
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "branch": null,
 "dirty": false,
 "error": null,
 "full-revisionid": "3c379ea50459a6b538529523c2bafe14c1c8dfc7",
 "version": "0.16.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
